# Xcode Cloud Configuration for PRE iOS App
# This file configures Xcode Cloud to use the workspace instead of the project file

version: 1

# Build configuration
build:
  # Use the workspace file instead of the project file
  scheme: App
  workspace: ios/App/App.xcworkspace
  
  # Environment variables
  environment:
    CI_XCODE_PROJECT: ios/App/App.xcworkspace
    
  # Pre-build actions
  pre_build:
    - script: ci_scripts/ci_post_clone.sh
    - script: ci_scripts/ci_pre_xcodebuild.sh

# Test configuration (if needed)
test:
  scheme: App
  workspace: ios/App/App.xcworkspace
